### ISSUE TITLE
It's an awful lot of code for a hello world

### ISSUE THREAD

**Issue by kennethlynne** [MitocGroup/deep-microservices-helloworld#17]
Tried looking up DEEP, and it was hard to get the idea of how to work with it, so a hello world should  make this all clear, or so I thought. 

Just wanted you to reconsider and make the hello world example as canonical as possible, as it is quite off-putting in its current state for new developers.

Is really a concept of models necessary? And tests? And validation, front-end etc?
Not for a hello world, but sure would be nice with those examples too, in separate repositories as soon as a basic hello world is understood.

**Comment by eistrati** [comment]
@kennethlynne Thank you very much for your feedback! We are really sorry that current state of the platform is quite complex and we would like to improve it (reduce the complexity). Indeed, we are considering to simplify hello world repository, as well as open source other repositories that would make it easier for others to understand and engage with DEEP ecosystem.

To answer your questions, I would agree that concepts of validation, tests, and similar is not necessary in hello world, but front-end + back-end + data (tiers) are vital to seamless functioning of this platform. So, again, let us work in the next couple of days on reducing the codebase, as well as improving the documentation.

**Comment by eistrati** [comment]
We have worked to simplify the codebase. Everything you need to know is summarized here: https://github.com/MitocGroup/deep-microservices-helloworld/tree/master/src/DeepHelloWorld

We have also updated the README file to summarize the important points: https://github.com/MitocGroup/deep-microservices-helloworld/blob/master/README.md

We are now working to simplify the documentation and create some more tutorials + videos that will show the value of this approach.

We'll close this issue now, but feel free to reopen or create new ones if you see other problems.
